font_size 10
background #2c2c2c
foreground #e5e5e5
color0 #2c2c2c
color8 #3c3c3c
color15 #ffffff
clipboard_control write-primary write-clipboard read-clipboard
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
term xterm-256color
