[colors]
draw_bold_text_with_bright_colors = true

[terminal]
osc52 = "CopyPaste"

[colors.bright]
black = "0x686868"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.cursor]
cursor = "0xffffff"
text = "0x2a2a2a"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xc7c7c7"
yellow = "0xe6c547"

[colors.primary]
background = "0x2a2a2a"
foreground = "0xeaeaea"

[window]
decorations = "None"
padding.y = 10

[font]
normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"
size = 9.0

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"
